services:
  badgehub-frontend:
    build: .
    ports:
      - "8003:3000"
    restart: always
    env_file:
      - ".env.prod"
    networks:
      - badgehub_network

networks:
  badgehub_network:
    name: badgehub_network
    external: true
