services:
  badgehub-frontend:
    image: ghcr.io/badgeteam/badgehub-frontend:${FRONTEND_IMAGE_TAG:-latest}
    ports:
      - "8001:3000"
    restart: always
    env_file:
      - .env.prod
    environment:
      FRONTEND_IMAGE_TAG: "${FRONTEND_IMAGE_TAG}"
    networks:
      - badgehub_network

networks:
  badgehub_network:
    name: badgehub_network
    external: true
